### ISSUE TITLE
Add ability to remove navbar in Customizer

### ISSUE THREAD

**Issue by matt-bernhardt** [MITLibraries/courtyard#14]
There's a use case in the Blog child theme for the complete removal of the navbar. Rather than re-creating the header there and removing the markup, it may make sense to convert the navbar to a region and allow site creators to just empty it when needed.

**Comment by matt-bernhardt** [comment]
After a bit of playing, it looks like the better course of action is to add a theme setting to suppress the navbar. This is accessed in the Customizer, in the Nav option. Check the box labeled "Hide Nav" to prevent the navbar from being rendered.

**Comment by matt-bernhardt** [comment]
This has been deployed to the test server. @frrrances can you review there please?

**Comment by frrrances** [comment]
The nav bar is gone! lgtm :+1:
